# ~/.dotfiles/nushell/config.nu  (symlinked to ~/.config/nushell/config.nu)

# Disable nushell's own startup banner — we use fastfetch instead.
$env.config.show_banner = false

# System-info banner, only when attached to a real terminal.
if (is-terminal --stdout) and (which fastfetch | is-not-empty) {
    ^fastfetch
}

# Modern CLI replacements. nushell keeps its own structured `ls`; these add the
# eza/bat conveniences on top. (zoxide's `z`/`zi` come from the vendor autoload
# dir, generated by gen-integrations.nu.)
alias ll = eza -l --icons --git --group-directories-first
alias la = eza -la --icons --git --group-directories-first
alias lt = eza --tree --level=2 --icons
alias cat = bat
